// // Mocks generated by Mockito 5.4.4 from annotations
// // in pbl5_menu/test/app_initializer_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i12;
// import 'dart:convert' as _i16;
// import 'dart:io' as _i5;
// import 'dart:typed_data' as _i17;
// import 'dart:ui' as _i9;

// import 'package:audioplayers/audioplayers.dart' as _i8;
// import 'package:camera/camera.dart' as _i2;
// import 'package:flutter/material.dart' as _i6;
// import 'package:http/http.dart' as _i3;
// import 'package:mockito/mockito.dart' as _i1;
// import 'package:mockito/src/dummies.dart' as _i13;
// import 'package:pbl5_menu/features/voice_commands.dart' as _i15;
// import 'package:pbl5_menu/services/picture_service.dart' as _i4;
// import 'package:pbl5_menu/services/stt/stt_service.dart' as _i10;
// import 'package:pbl5_menu/services/tts/tts_service_google.dart' as _i11;
// import 'package:pbl5_menu/shared/database_helper.dart' as _i14;
// import 'package:sqflite/sqflite.dart' as _i7;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeCameraController_0 extends _i1.SmartFake
//     implements _i2.CameraController {
//   _FakeCameraController_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
//   _FakeClient_1(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeImageDecoder_2 extends _i1.SmartFake implements _i4.ImageDecoder {
//   _FakeImageDecoder_2(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeMultipartFileWrapper_3 extends _i1.SmartFake
//     implements _i4.MultipartFileWrapper {
//   _FakeMultipartFileWrapper_3(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeFile_4 extends _i1.SmartFake implements _i5.File {
//   _FakeFile_4(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeMultipartRequest_5 extends _i1.SmartFake
//     implements _i3.MultipartRequest {
//   _FakeMultipartRequest_5(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeWidget_6 extends _i1.SmartFake implements _i6.Widget {
//   _FakeWidget_6(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );

//   @override
//   String toString({_i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info}) =>
//       super.toString();
// }

// class _FakeDatabase_7 extends _i1.SmartFake implements _i7.Database {
//   _FakeDatabase_7(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeAudioPlayer_8 extends _i1.SmartFake implements _i8.AudioPlayer {
//   _FakeAudioPlayer_8(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeLocale_9 extends _i1.SmartFake implements _i9.Locale {
//   _FakeLocale_9(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeSttService_10 extends _i1.SmartFake implements _i10.SttService {
//   _FakeSttService_10(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeTtsServiceGoogle_11 extends _i1.SmartFake
//     implements _i11.TtsServiceGoogle {
//   _FakeTtsServiceGoogle_11(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeBuildContext_12 extends _i1.SmartFake implements _i6.BuildContext {
//   _FakeBuildContext_12(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeResponse_13 extends _i1.SmartFake implements _i3.Response {
//   _FakeResponse_13(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeStreamedResponse_14 extends _i1.SmartFake
//     implements _i3.StreamedResponse {
//   _FakeStreamedResponse_14(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// /// A class which mocks [PictureService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockPictureService extends _i1.Mock implements _i4.PictureService {
//   MockPictureService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i2.CameraController get controller => (super.noSuchMethod(
//         Invocation.getter(#controller),
//         returnValue: _FakeCameraController_0(
//           this,
//           Invocation.getter(#controller),
//         ),
//       ) as _i2.CameraController);

//   @override
//   set controller(_i2.CameraController? _controller) => super.noSuchMethod(
//         Invocation.setter(
//           #controller,
//           _controller,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i3.Client get httpClient => (super.noSuchMethod(
//         Invocation.getter(#httpClient),
//         returnValue: _FakeClient_1(
//           this,
//           Invocation.getter(#httpClient),
//         ),
//       ) as _i3.Client);

//   @override
//   set httpClient(_i3.Client? _httpClient) => super.noSuchMethod(
//         Invocation.setter(
//           #httpClient,
//           _httpClient,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   bool get isCameraInitialized => (super.noSuchMethod(
//         Invocation.getter(#isCameraInitialized),
//         returnValue: false,
//       ) as bool);

//   @override
//   set isCameraInitialized(bool? _isCameraInitialized) => super.noSuchMethod(
//         Invocation.setter(
//           #isCameraInitialized,
//           _isCameraInitialized,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i4.ImageDecoder get imageDecoder => (super.noSuchMethod(
//         Invocation.getter(#imageDecoder),
//         returnValue: _FakeImageDecoder_2(
//           this,
//           Invocation.getter(#imageDecoder),
//         ),
//       ) as _i4.ImageDecoder);

//   @override
//   set imageDecoder(_i4.ImageDecoder? _imageDecoder) => super.noSuchMethod(
//         Invocation.setter(
//           #imageDecoder,
//           _imageDecoder,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i4.MultipartFileWrapper get multipartFileWrapper => (super.noSuchMethod(
//         Invocation.getter(#multipartFileWrapper),
//         returnValue: _FakeMultipartFileWrapper_3(
//           this,
//           Invocation.getter(#multipartFileWrapper),
//         ),
//       ) as _i4.MultipartFileWrapper);

//   @override
//   set multipartFileWrapper(_i4.MultipartFileWrapper? _multipartFileWrapper) =>
//       super.noSuchMethod(
//         Invocation.setter(
//           #multipartFileWrapper,
//           _multipartFileWrapper,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i5.File Function(String) get fileFactory => (super.noSuchMethod(
//         Invocation.getter(#fileFactory),
//         returnValue: (String path) => _FakeFile_4(
//           this,
//           Invocation.getter(#fileFactory),
//         ),
//       ) as _i5.File Function(String));

//   @override
//   set fileFactory(_i5.File Function(String)? _fileFactory) =>
//       super.noSuchMethod(
//         Invocation.setter(
//           #fileFactory,
//           _fileFactory,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i4.MultipartRequestFactory get multipartRequestFactory =>
//       (super.noSuchMethod(
//         Invocation.getter(#multipartRequestFactory),
//         returnValue: (
//           String method,
//           Uri url,
//         ) =>
//             _FakeMultipartRequest_5(
//           this,
//           Invocation.getter(#multipartRequestFactory),
//         ),
//       ) as _i4.MultipartRequestFactory);

//   @override
//   set multipartRequestFactory(
//           _i4.MultipartRequestFactory? _multipartRequestFactory) =>
//       super.noSuchMethod(
//         Invocation.setter(
//           #multipartRequestFactory,
//           _multipartRequestFactory,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i12.Future<void> setupCamera() => (super.noSuchMethod(
//         Invocation.method(
//           #setupCamera,
//           [],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<void> initializeCamera() => (super.noSuchMethod(
//         Invocation.method(
//           #initializeCamera,
//           [],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   void disposeCamera() => super.noSuchMethod(
//         Invocation.method(
//           #disposeCamera,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i6.Widget getCameraPreview() => (super.noSuchMethod(
//         Invocation.method(
//           #getCameraPreview,
//           [],
//         ),
//         returnValue: _FakeWidget_6(
//           this,
//           Invocation.method(
//             #getCameraPreview,
//             [],
//           ),
//         ),
//       ) as _i6.Widget);

//   @override
//   _i12.Future<void> takePicture({
//     required String? endpoint,
//     required dynamic Function(List<dynamic>)? onLabelsDetected,
//     required dynamic Function(Duration)? onResponseTimeUpdated,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #takePicture,
//           [],
//           {
//             #endpoint: endpoint,
//             #onLabelsDetected: onLabelsDetected,
//             #onResponseTimeUpdated: onResponseTimeUpdated,
//           },
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<String> captureAndProcessImage() => (super.noSuchMethod(
//         Invocation.method(
//           #captureAndProcessImage,
//           [],
//         ),
//         returnValue: _i12.Future<String>.value(_i13.dummyValue<String>(
//           this,
//           Invocation.method(
//             #captureAndProcessImage,
//             [],
//           ),
//         )),
//       ) as _i12.Future<String>);

//   @override
//   _i12.Future<void> sendImageAndHandleResponse(
//     String? filePath,
//     String? endpoint,
//     dynamic Function(List<String>)? onDetectedObjects,
//     dynamic Function(Duration)? onResponseTime,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #sendImageAndHandleResponse,
//           [
//             filePath,
//             endpoint,
//             onDetectedObjects,
//             onResponseTime,
//           ],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   List<String> parseLabelsFromResponse(String? responseBody) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #parseLabelsFromResponse,
//           [responseBody],
//         ),
//         returnValue: <String>[],
//       ) as List<String>);
// }

// /// A class which mocks [DatabaseHelper].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockDatabaseHelper extends _i1.Mock implements _i14.DatabaseHelper {
//   MockDatabaseHelper() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   set database(_i12.Future<_i7.Database>? db) => super.noSuchMethod(
//         Invocation.setter(
//           #database,
//           db,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i12.Future<_i7.Database> get database => (super.noSuchMethod(
//         Invocation.getter(#database),
//         returnValue: _i12.Future<_i7.Database>.value(_FakeDatabase_7(
//           this,
//           Invocation.getter(#database),
//         )),
//       ) as _i12.Future<_i7.Database>);

//   @override
//   _i12.Future<void> onCreate(
//     _i7.Database? db,
//     int? version,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #onCreate,
//           [
//             db,
//             version,
//           ],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<void> onUpgrade(
//     _i7.Database? db,
//     int? oldVersion,
//     int? newVersion,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #onUpgrade,
//           [
//             db,
//             oldVersion,
//             newVersion,
//           ],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<void> insertDefaultData(_i7.Database? db) => (super.noSuchMethod(
//         Invocation.method(
//           #insertDefaultData,
//           [db],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<void> insertContact(String? name) => (super.noSuchMethod(
//         Invocation.method(
//           #insertContact,
//           [name],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<List<String>> getContacts() => (super.noSuchMethod(
//         Invocation.method(
//           #getContacts,
//           [],
//         ),
//         returnValue: _i12.Future<List<String>>.value(<String>[]),
//       ) as _i12.Future<List<String>>);

//   @override
//   _i12.Future<void> deleteContact(String? name) => (super.noSuchMethod(
//         Invocation.method(
//           #deleteContact,
//           [name],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<Map<String, dynamic>> getPreferences() => (super.noSuchMethod(
//         Invocation.method(
//           #getPreferences,
//           [],
//         ),
//         returnValue:
//             _i12.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
//       ) as _i12.Future<Map<String, dynamic>>);

//   @override
//   _i12.Future<void> updatePreferences(
//     double? fontSize,
//     String? language,
//     bool? isDarkTheme,
//     double? speechRate,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #updatePreferences,
//           [
//             fontSize,
//             language,
//             isDarkTheme,
//             speechRate,
//           ],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<Map<String, String>> getTtsSettings() => (super.noSuchMethod(
//         Invocation.method(
//           #getTtsSettings,
//           [],
//         ),
//         returnValue: _i12.Future<Map<String, String>>.value(<String, String>{}),
//       ) as _i12.Future<Map<String, String>>);

//   @override
//   _i12.Future<void> updateTtsSettings(
//     String? languageCode,
//     String? voiceName,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #updateTtsSettings,
//           [
//             languageCode,
//             voiceName,
//           ],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<void> resetDatabase() => (super.noSuchMethod(
//         Invocation.method(
//           #resetDatabase,
//           [],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);
// }

// /// A class which mocks [TtsServiceGoogle].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockTtsServiceGoogle extends _i1.Mock implements _i11.TtsServiceGoogle {
//   MockTtsServiceGoogle() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i8.AudioPlayer get audioPlayer => (super.noSuchMethod(
//         Invocation.getter(#audioPlayer),
//         returnValue: _FakeAudioPlayer_8(
//           this,
//           Invocation.getter(#audioPlayer),
//         ),
//       ) as _i8.AudioPlayer);

//   @override
//   set audioPlayer(_i8.AudioPlayer? _audioPlayer) => super.noSuchMethod(
//         Invocation.setter(
//           #audioPlayer,
//           _audioPlayer,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   String get languageCode => (super.noSuchMethod(
//         Invocation.getter(#languageCode),
//         returnValue: _i13.dummyValue<String>(
//           this,
//           Invocation.getter(#languageCode),
//         ),
//       ) as String);

//   @override
//   set languageCode(String? _languageCode) => super.noSuchMethod(
//         Invocation.setter(
//           #languageCode,
//           _languageCode,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   String get voiceName => (super.noSuchMethod(
//         Invocation.getter(#voiceName),
//         returnValue: _i13.dummyValue<String>(
//           this,
//           Invocation.getter(#voiceName),
//         ),
//       ) as String);

//   @override
//   set voiceName(String? _voiceName) => super.noSuchMethod(
//         Invocation.setter(
//           #voiceName,
//           _voiceName,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   double get speechRate => (super.noSuchMethod(
//         Invocation.getter(#speechRate),
//         returnValue: 0.0,
//       ) as double);

//   @override
//   set speechRate(double? _speechRate) => super.noSuchMethod(
//         Invocation.setter(
//           #speechRate,
//           _speechRate,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void initializeTts() => super.noSuchMethod(
//         Invocation.method(
//           #initializeTts,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i12.Future<void> updateLanguage(
//     String? newLanguageCode,
//     String? newVoiceName,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #updateLanguage,
//           [
//             newLanguageCode,
//             newVoiceName,
//           ],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<void> updateSpeechRate(double? newSpeechRate) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #updateSpeechRate,
//           [newSpeechRate],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<void> speakLabels(List<dynamic>? detectedObjects) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #speakLabels,
//           [detectedObjects],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);
// }

// /// A class which mocks [SttService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockSttService extends _i1.Mock implements _i10.SttService {
//   MockSttService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i12.Future<void> initializeStt() => (super.noSuchMethod(
//         Invocation.method(
//           #initializeStt,
//           [],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<void> startListening(dynamic Function(String)? onResult) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #startListening,
//           [onResult],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   void stopListening() => super.noSuchMethod(
//         Invocation.method(
//           #stopListening,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void restartListening() => super.noSuchMethod(
//         Invocation.method(
//           #restartListening,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );
// }

// /// A class which mocks [VoiceCommands].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockVoiceCommands extends _i1.Mock implements _i15.VoiceCommands {
//   MockVoiceCommands() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i8.AudioPlayer get player => (super.noSuchMethod(
//         Invocation.getter(#player),
//         returnValue: _FakeAudioPlayer_8(
//           this,
//           Invocation.getter(#player),
//         ),
//       ) as _i8.AudioPlayer);

//   @override
//   Map<String, List<String>> get voiceCommands => (super.noSuchMethod(
//         Invocation.getter(#voiceCommands),
//         returnValue: <String, List<String>>{},
//       ) as Map<String, List<String>>);

//   @override
//   set voiceCommands(Map<String, List<String>>? _voiceCommands) =>
//       super.noSuchMethod(
//         Invocation.setter(
//           #voiceCommands,
//           _voiceCommands,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i9.Locale get locale => (super.noSuchMethod(
//         Invocation.getter(#locale),
//         returnValue: _FakeLocale_9(
//           this,
//           Invocation.getter(#locale),
//         ),
//       ) as _i9.Locale);

//   @override
//   set locale(_i9.Locale? _locale) => super.noSuchMethod(
//         Invocation.setter(
//           #locale,
//           _locale,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i10.SttService get sttService => (super.noSuchMethod(
//         Invocation.getter(#sttService),
//         returnValue: _FakeSttService_10(
//           this,
//           Invocation.getter(#sttService),
//         ),
//       ) as _i10.SttService);

//   @override
//   set sttService(_i10.SttService? _sttService) => super.noSuchMethod(
//         Invocation.setter(
//           #sttService,
//           _sttService,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i11.TtsServiceGoogle get ttsServiceGoogle => (super.noSuchMethod(
//         Invocation.getter(#ttsServiceGoogle),
//         returnValue: _FakeTtsServiceGoogle_11(
//           this,
//           Invocation.getter(#ttsServiceGoogle),
//         ),
//       ) as _i11.TtsServiceGoogle);

//   @override
//   set ttsServiceGoogle(_i11.TtsServiceGoogle? _ttsServiceGoogle) =>
//       super.noSuchMethod(
//         Invocation.setter(
//           #ttsServiceGoogle,
//           _ttsServiceGoogle,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i6.BuildContext get context => (super.noSuchMethod(
//         Invocation.getter(#context),
//         returnValue: _FakeBuildContext_12(
//           this,
//           Invocation.getter(#context),
//         ),
//       ) as _i6.BuildContext);

//   @override
//   set context(_i6.BuildContext? _context) => super.noSuchMethod(
//         Invocation.setter(
//           #context,
//           _context,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   List<String> get activationCommands => (super.noSuchMethod(
//         Invocation.getter(#activationCommands),
//         returnValue: <String>[],
//       ) as List<String>);

//   @override
//   set activationCommands(List<String>? _activationCommands) =>
//       super.noSuchMethod(
//         Invocation.setter(
//           #activationCommands,
//           _activationCommands,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   Map<String, bool> get widgetStates => (super.noSuchMethod(
//         Invocation.getter(#widgetStates),
//         returnValue: <String, bool>{},
//       ) as Map<String, bool>);

//   @override
//   set widgetStates(Map<String, bool>? _widgetStates) => super.noSuchMethod(
//         Invocation.setter(
//           #widgetStates,
//           _widgetStates,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void setContext(
//     _i6.BuildContext? context,
//     _i9.Locale? locale,
//   ) =>
//       super.noSuchMethod(
//         Invocation.method(
//           #setContext,
//           [
//             context,
//             locale,
//           ],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i12.Future<void> loadVoiceCommands() => (super.noSuchMethod(
//         Invocation.method(
//           #loadVoiceCommands,
//           [],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   _i12.Future<void> loadActivationCommands() => (super.noSuchMethod(
//         Invocation.method(
//           #loadActivationCommands,
//           [],
//         ),
//         returnValue: _i12.Future<void>.value(),
//         returnValueForMissingStub: _i12.Future<void>.value(),
//       ) as _i12.Future<void>);

//   @override
//   void startListening() => super.noSuchMethod(
//         Invocation.method(
//           #startListening,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   int levenshteinDistance(
//     String? s1,
//     String? s2,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #levenshteinDistance,
//           [
//             s1,
//             s2,
//           ],
//         ),
//         returnValue: 0,
//       ) as int);

//   @override
//   double calculateSimilarity(
//     String? s1,
//     String? s2,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #calculateSimilarity,
//           [
//             s1,
//             s2,
//           ],
//         ),
//         returnValue: 0.0,
//       ) as double);
// }

// /// A class which mocks [Client].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockClient extends _i1.Mock implements _i3.Client {
//   MockClient() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i12.Future<_i3.Response> head(
//     Uri? url, {
//     Map<String, String>? headers,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #head,
//           [url],
//           {#headers: headers},
//         ),
//         returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_13(
//           this,
//           Invocation.method(
//             #head,
//             [url],
//             {#headers: headers},
//           ),
//         )),
//       ) as _i12.Future<_i3.Response>);

//   @override
//   _i12.Future<_i3.Response> get(
//     Uri? url, {
//     Map<String, String>? headers,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #get,
//           [url],
//           {#headers: headers},
//         ),
//         returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_13(
//           this,
//           Invocation.method(
//             #get,
//             [url],
//             {#headers: headers},
//           ),
//         )),
//       ) as _i12.Future<_i3.Response>);

//   @override
//   _i12.Future<_i3.Response> post(
//     Uri? url, {
//     Map<String, String>? headers,
//     Object? body,
//     _i16.Encoding? encoding,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #post,
//           [url],
//           {
//             #headers: headers,
//             #body: body,
//             #encoding: encoding,
//           },
//         ),
//         returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_13(
//           this,
//           Invocation.method(
//             #post,
//             [url],
//             {
//               #headers: headers,
//               #body: body,
//               #encoding: encoding,
//             },
//           ),
//         )),
//       ) as _i12.Future<_i3.Response>);

//   @override
//   _i12.Future<_i3.Response> put(
//     Uri? url, {
//     Map<String, String>? headers,
//     Object? body,
//     _i16.Encoding? encoding,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #put,
//           [url],
//           {
//             #headers: headers,
//             #body: body,
//             #encoding: encoding,
//           },
//         ),
//         returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_13(
//           this,
//           Invocation.method(
//             #put,
//             [url],
//             {
//               #headers: headers,
//               #body: body,
//               #encoding: encoding,
//             },
//           ),
//         )),
//       ) as _i12.Future<_i3.Response>);

//   @override
//   _i12.Future<_i3.Response> patch(
//     Uri? url, {
//     Map<String, String>? headers,
//     Object? body,
//     _i16.Encoding? encoding,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #patch,
//           [url],
//           {
//             #headers: headers,
//             #body: body,
//             #encoding: encoding,
//           },
//         ),
//         returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_13(
//           this,
//           Invocation.method(
//             #patch,
//             [url],
//             {
//               #headers: headers,
//               #body: body,
//               #encoding: encoding,
//             },
//           ),
//         )),
//       ) as _i12.Future<_i3.Response>);

//   @override
//   _i12.Future<_i3.Response> delete(
//     Uri? url, {
//     Map<String, String>? headers,
//     Object? body,
//     _i16.Encoding? encoding,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #delete,
//           [url],
//           {
//             #headers: headers,
//             #body: body,
//             #encoding: encoding,
//           },
//         ),
//         returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_13(
//           this,
//           Invocation.method(
//             #delete,
//             [url],
//             {
//               #headers: headers,
//               #body: body,
//               #encoding: encoding,
//             },
//           ),
//         )),
//       ) as _i12.Future<_i3.Response>);

//   @override
//   _i12.Future<String> read(
//     Uri? url, {
//     Map<String, String>? headers,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #read,
//           [url],
//           {#headers: headers},
//         ),
//         returnValue: _i12.Future<String>.value(_i13.dummyValue<String>(
//           this,
//           Invocation.method(
//             #read,
//             [url],
//             {#headers: headers},
//           ),
//         )),
//       ) as _i12.Future<String>);

//   @override
//   _i12.Future<_i17.Uint8List> readBytes(
//     Uri? url, {
//     Map<String, String>? headers,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #readBytes,
//           [url],
//           {#headers: headers},
//         ),
//         returnValue: _i12.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
//       ) as _i12.Future<_i17.Uint8List>);

//   @override
//   _i12.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #send,
//           [request],
//         ),
//         returnValue:
//             _i12.Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_14(
//           this,
//           Invocation.method(
//             #send,
//             [request],
//           ),
//         )),
//       ) as _i12.Future<_i3.StreamedResponse>);

//   @override
//   void close() => super.noSuchMethod(
//         Invocation.method(
//           #close,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );
// }
