name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - ai-model-develop

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ai-models    

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install ultralytics \
            torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 \
            fastapi uvicorn python-multipart \
            flask flask-cors \
            opencv-python opencv-python-headless \
            onnx==1.16.1 onnxruntime onnxruntime-gpu \
            tensorflow openvino==2024.6.0 pytesseract \
            symspellpy \
            pytest pytest-cov httpx

      - name: Run tests with coverage
        run: |
          pytest tests/ --cov=. --cov-report=xml

      - name: SonarCloud Scan
        run: |
          sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_PY_TOKEN }}
