name: SonarQube Analysis

on:
  push:
    branches:
      - mobile-CI
  pull_request:

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile-app  # Establece el directorio de trabajo predeterminado para todos los pasos

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.7.0
        with:
          flutter-version: '3.24.5'
          
      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Generate Coverage Report
        run: flutter test --coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=pbl5
            -Dsonar.organization=oier-22
            -Dsonar.projectBaseDir=mobile-app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          SONAR_HOST_URL: "https://sonarcloud.io"
