name: SonarQube Analysis

on:
  push:
    branches:
      - mobile-CI
  pull_request:

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.7.0
        with:
          flutter-version: '3.13.0'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Generate Coverage Report
        run: flutter test --coverage

      - name: Run SonarQube Analysis
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
