name: SonarQube Analysis

on:
  push:
    branches:
      - mobile-CI
  pull_request:

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.7.0
        with:
          flutter-version: '3.24.5'

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Generate Coverage Report
        run: flutter test --coverage

      - name: Verify Dart Installation
        run: dart --version

      - name: Check Coverage File
        run: ls -la coverage/lcov.info

      - name: Set up SonarQube scanner
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-project-key: 'your-project-key'
          sonar-host-url: 'https://sonarcloud.io'

      - name: Run SonarQube analysis
        run: |
          sonar-scanner
        working-directory: ./mobile-app
