name: SonarQube Analysis

on:
  push:
    branches:
      - mobile-CI
  pull_request:

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.7.0
        with:
          flutter-version: '3.24.5'
          
      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Install Flutter dependencies
        working-directory: mobile-app
        run: flutter pub get

      - name: Generate Coverage Report
        working-directory: mobile-app
        run: flutter test --coverage

      - name: Install SonarScanner
        run: |
          # Download SonarScanner
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip -d $HOME
          # Set SONAR_SCANNER_HOME and update PATH
          echo "SONAR_SCANNER_HOME=$HOME/sonar-scanner-5.0.1.3006-linux" >> $GITHUB_ENV
          echo "PATH=$HOME/sonar-scanner-5.0.1.3006-linux/bin:$PATH" >> $GITHUB_ENV


      - name: Run SonarQube Analysis
        working-directory: mobile-app
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
